text = "  python backend learning  "
print("Original Text:", text)
print("\n--- Case Conversion ---")
print("Upper:", text.upper())
print("Lower:", text.lower())
print("Title:", text.title())
print("Capitalize:", text.capitalize())
print("in the given function we can remove the unwanted space")
print("\n--- Strip Functions ---")
print("Strip:", text.strip())
print("Left Strip:", text.lstrip())
print("Right Strip:", text.rstrip())
print("\n--- Split & Join ---")
words = text.strip().split()
print("Split:", words)
print("Join with - :", "-".join(words))
print("Using this function we count number of the chaarcter present")
print("Count 'n':", text.count("n"))

print("using this function we check the string")
print("\n--- Type Check ---")
print("Is Alpha:", "Hello".isalpha())
print("Is Digit:", "12345".isdigit())
print("Is Alnum:", "Python123".isalnum())
print("Is Lower:", "hello".islower())
print("Is Upper:", "HELLO".isupper())
print("Here is our practice quetion")
print("\n--- Practical Example ---")
password = "Backend@123"
hidden = password[0] + "*" * (len(password)-2) + password[-1]
print("Hidden Password:", hidden)
