f = open("E:\\Programing\\Python\\Day-8\\demo.txt","r")
data = f.readline()
data1 = f.readline()
data2 = f.readline()
data0 = f.read()
print(data)
print(data1)
print(data2)
print(data0)
print(type(data))
f.close()
